@apiUrl = http://localhost:5000
@flightServiceUrl = http://localhost:5005
@identityServiceUrl = http://localhost:5010
@airplanesServiceUrl = http://localhost:5015
@flightId = 4a54c1c6-f12b-43f2-9676-ad99bb02ece0
@airplaneId = 76D6E7AE-43D5-4375-B56F-7B5F8F4B215A
@jwtToken = 

#########################################################
############## API GATEWAY HEALTHCHECK ##################
#########################################################
GET {{apiUrl}}/api/Home
###
GET {{flightServiceUrl}}/api/Home
###
GET {{identityServiceUrl}}/Home
###
GET {{airplanesServiceUrl}}/api/Home

#########################################################
################## IDENTITY SERVICE #####################
#########################################################

GET {{identityServiceUrl}}/Me
Authorization: Bearer {{jwtToken}}

### SIGN UP ###
POST {{identityServiceUrl}}/sign-up
Content-Type: application/json

{
	"email": "test1@test.com",
	"password": "123qwe"
}

### SIGN IN ###
POST {{identityServiceUrl}}/sign-in
Content-Type: application/json

{
	"email": "test1@test.com",
	"password": "123qwe"
}

#########################################################
################### FLIGHTS SERVICE #####################
#########################################################

### GET FLIGHT ###
GET {{flightServiceUrl}}/flights/{{flightId}}
Content-Type: application/json

### BROWSE FLIGHTS ###
GET {{apiUrl}}/flights?page=1&pageSize=15
Content-Type: application/json

### CREATE FLIGHT ###
POST {{apiUrl}}/Flights
Content-Type: application/json

{
	"planeId": "{{airplaneId}}",
	"startAirport": "5ba47457-437e-4efc-b724-a49b3d1aac89",
	"transferAirports": [
		"81053718-af52-4f50-9a53-0e4a51525c3a"
	],
	"endAirport": "d99d11aa-fbc9-418b-b355-c4e416223f47",
	"flightType": "RoundTrip",
	"flightDate": "9/21/2019 8:36:07 PM",
	"returnDate": "9/30/2019 12:00:00 PM"
}

### DELETE FLIGHT ###

DELETE {{apiUrl}}/Flights/{{flightId}}
Content-Type: application/json

### END FLIGHT ###

PATCH {{apiUrl}}/Flights/{{flightId}}
Content-Type: application/json

#########################################################
################### AIRPLANES SERVICE ###################
#########################################################

### CREATE AIRPLANE ###
POST {{apiUrl}}/Airplanes
Content-Type: application/json

{
	"model": "Boeing 757",
	"availableSeats": {
			"economic": 150,
			"business": 50
		},
	"introductionToTheFleet": "11/7/2019 8:36:07 PM",
}

### BROWSE AIRPLANES ###
GET {{airplanesServiceUrl}}/Airplanes?page=1&pageSize=100
Content-Type: application/json